"""Single source of truth for every configuration option.

Everything else is generated from this file:

* defaults for a brand-new appliance
* type coercion + validation when a value arrives from YAML, the environment
  or the Settings web page
* the Settings web page itself (groups, labels, help text, widgets)
* ``config/config.example.yaml`` and the options table in the README
  (both regenerated by ``scripts/gen-config-docs.py``)

Adding a new option means adding one ``Field`` below. No other file needs to
change, which is what keeps the appliance easy to maintain.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Iterable

# ---------------------------------------------------------------------------
# Field definition
# ---------------------------------------------------------------------------

#: Widget/coercion types understood by the config loader and the Settings UI.
TYPES = ("str", "text", "int", "float", "bool", "choice", "list", "password")


@dataclass(frozen=True)
class Field:
    """One configuration option."""

    key: str
    type: str
    default: Any
    group: str
    label: str
    help: str = ""
    choices: tuple[str, ...] = ()
    #: Inclusive bounds for numeric fields.
    minimum: float | None = None
    maximum: float | None = None
    #: Secrets are redacted in logs and in ``GET /api/settings``.
    secret: bool = False
    #: Hidden behind "Advanced" in the Settings UI.
    advanced: bool = False
    #: systemd units that must be restarted for a change to take effect.
    restart_units: tuple[str, ...] = ()
    #: Optional extra validator: return None if OK, or an error string.
    validator: Callable[[Any], str | None] | None = None
    #: Placeholder shown in the Settings UI when empty.
    placeholder: str = ""
    #: ``inputmode`` for the text box, which is what decides the on-screen
    #: keyboard a phone offers. Only worth setting where the default keyboard
    #: is wrong — a PIN wants digits, an API key very much does not.
    inputmode: str = ""

    def __post_init__(self) -> None:  # pragma: no cover - developer guard
        if self.type not in TYPES:
            raise ValueError(f"{self.key}: unknown field type {self.type!r}")


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------


def _validate_url_or_empty(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text:
        return None
    lowered = text.lower()
    ok_prefixes = ("http://", "https://", "webcal://", "file://", "/")
    if not lowered.startswith(ok_prefixes):
        return "Must start with https://, http://, webcal://, file:// or / (a local path)."
    return None


def _validate_timezone(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        from zoneinfo import ZoneInfo

        ZoneInfo(text)
    except Exception:
        return "Unknown time zone. Use an IANA name such as Europe/London or Asia/Singapore."
    return None


def _validate_host(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text:
        return "Cannot be empty. Use 127.0.0.1 to keep the dashboard private."
    return None


def _validate_pin(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text:
        return None
    if not text.isdigit():
        return "The admin PIN must be digits only (it is typed on a TV remote)."
    if len(text) < 4:
        return "Use at least 4 digits."
    return None


def _validate_email_or_empty(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text:
        return None
    if text.count("@") != 1 or text.startswith("@") or text.endswith("@") or " " in text:
        return "Must be a single email address, e.g. room@example.com."
    return None


def _validate_email_list(value: Any) -> str | None:
    items = value if isinstance(value, (list, tuple)) else str(value or "").splitlines()
    bad = [
        str(item).strip()
        for item in items
        if str(item).strip() and _validate_email_or_empty(item) is not None
    ]
    if bad:
        return f"Not an email address: {', '.join(bad[:3])}"
    return None


def _validate_api_key_or_empty(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text:
        return None
    if " " in text or "\n" in text:
        return "An API key has no spaces in it — check for a stray copy/paste."
    if len(text) < 20:
        return "That looks too short to be an API key."
    return None


# ---------------------------------------------------------------------------
# Groups (order = order of sections in the Settings UI)
# ---------------------------------------------------------------------------

GROUPS: tuple[tuple[str, str], ...] = (
    ("room", "Room"),
    ("calendar", "Calendar"),
    ("meetings", "Meeting joining"),
    ("airplay", "AirPlay screen sharing"),
    ("audio", "Poly conference bar"),
    ("remote", "Poly remote / controller"),
    ("controller", "Room controller (phone)"),
    ("display", "Display & browser"),
    ("background", "Background & slideshow"),
    ("recovery", "Reliability & recovery"),
    ("minutes", "Meeting minutes (experimental)"),
    ("system", "System & access"),
)

GROUP_HELP: dict[str, str] = {
    "room": "What the room is called on screen.",
    "calendar": "Where the room's meetings come from. An ICS/iCal feed is the "
    "quickest way to get going; Microsoft Graph and Google Calendar can be "
    "dropped in later without touching the rest of the appliance.",
    "meetings": "How the appliance behaves around meeting start and end times.",
    "airplay": "Wireless screen sharing from a Mac, iPhone or iPad.",
    "audio": "The USB conference bar used as camera, microphone and speaker.",
    "remote": "Optional physical remote / controller buttons.",
    "controller": "The big-button page anyone in the room can open by scanning\n"
    "the QR code on the TV. It joins, leaves, mutes and changes the volume — and\n"
    "nothing else.",
    "display": "Chromium kiosk behaviour on the TV.",
    "background": "The wallpaper behind the dashboard. Upload your own photos "
    "and videos from the control panel and they rotate as a slideshow; a video "
    "plays all the way through before the next slide.",
    "recovery": "Self-healing. Leave these alone unless you have a reason.",
    "minutes": "Records each meeting, writes down who said what, and can email a "
    "summary to everyone who was there. Off by default, and every part of it is a "
    "separate switch. Recording people has legal and social consequences — tell the "
    "room, leave the on-screen notice on, and read docs/meeting-minutes.md before "
    "turning any of this on in a room real meetings happen in.",
    "system": "Ports, logging and administrative access.",
}


# ---------------------------------------------------------------------------
# The options
# ---------------------------------------------------------------------------

FIELDS: tuple[Field, ...] = (
    # -- Room ---------------------------------------------------------------
    Field(
        key="ROOM_NAME",
        type="str",
        default="Meeting Room",
        group="room",
        label="Room name",
        help="Shown in large type at the top of the dashboard.",
        placeholder="Meeting Room",
    ),
    Field(
        key="ROOM_SUBTITLE",
        type="str",
        default="",
        group="room",
        label="Room subtitle",
        help="Optional second line, e.g. a floor or capacity: “Level 3 · 8 seats”.",
        placeholder="Level 3 · 8 seats",
    ),
    Field(
        key="TIMEZONE",
        type="str",
        default="",
        group="room",
        label="Time zone",
        help="IANA time zone name. Leave empty to use the Raspberry Pi's own time zone.",
        placeholder="Europe/London",
        validator=_validate_timezone,
    ),
    Field(
        key="TIME_FORMAT_24H",
        type="bool",
        default=False,
        group="room",
        label="24-hour clock",
        help="Off shows 10:42 AM, on shows 10:42.",
    ),
    # -- Calendar -----------------------------------------------------------
    Field(
        key="CALENDAR_SOURCE",
        type="choice",
        default="ics",
        choices=("ics", "mock", "none"),
        group="calendar",
        label="Calendar source",
        help="“ics” uses the ICS/iCal URL below. “mock” invents meetings "
        "so you can test the screen without a real calendar. “none” disables "
        "the calendar entirely.",
    ),
    Field(
        key="CALENDAR_ICS_URL",
        type="str",
        default="",
        group="calendar",
        label="Calendar ICS/iCal URL",
        help="The room calendar's secret iCal address. Outlook: Calendar → Share → "
        "Publish a calendar → ICS link. Google: Calendar settings → Secret address "
        "in iCal format. A local file path also works.",
        placeholder="https://outlook.office365.com/owa/calendar/…/calendar.ics",
        secret=True,
        validator=_validate_url_or_empty,
    ),
    Field(
        key="CALENDAR_REFRESH_SECONDS",
        type="int",
        default=30,
        minimum=10,
        maximum=3600,
        group="calendar",
        label="Refresh interval (seconds)",
        help="How often the calendar is re-fetched. 30 seconds is a good default.",
    ),
    Field(
        key="CALENDAR_LOOKAHEAD_HOURS",
        type="int",
        default=24,
        minimum=1,
        maximum=168,
        group="calendar",
        label="Look-ahead window (hours)",
        help="How far into the future meetings are loaded.",
        advanced=True,
    ),
    Field(
        key="CALENDAR_UPCOMING_COUNT",
        type="int",
        default=4,
        minimum=1,
        maximum=8,
        group="calendar",
        label="Upcoming meetings to show",
        help="How many meetings are listed under “Upcoming” (3–5 fits a TV nicely).",
    ),
    Field(
        key="CALENDAR_TIMEOUT_SECONDS",
        type="int",
        default=20,
        minimum=3,
        maximum=120,
        group="calendar",
        label="Fetch timeout (seconds)",
        advanced=True,
    ),
    Field(
        key="CALENDAR_SHOW_TITLES",
        type="bool",
        default=True,
        group="calendar",
        label="Show meeting titles",
        help="Turn off for privacy: the dashboard then shows “Busy” instead of the subject.",
    ),
    Field(
        key="CALENDAR_IGNORE_ALL_DAY",
        type="bool",
        default=True,
        group="calendar",
        label="Ignore all-day events",
        help="All-day entries (out-of-office, holidays) do not mark the room busy.",
        advanced=True,
    ),
    Field(
        key="CALENDAR_IGNORE_DECLINED",
        type="bool",
        default=True,
        group="calendar",
        label="Ignore cancelled events",
        help="Skip events the organiser has cancelled.",
        advanced=True,
    ),
    # -- Meeting joining ----------------------------------------------------
    Field(
        key="AUTO_OPEN_MEETING",
        type="bool",
        default=True,
        group="meetings",
        label="Open meetings automatically",
        help="Navigate the TV to the meeting shortly before it starts.",
    ),
    Field(
        key="AUTO_OPEN_MINUTES",
        type="float",
        default=1.0,
        minimum=0.0,
        maximum=30.0,
        group="meetings",
        label="Open this many minutes early",
        help="1 means the meeting page opens about one minute before the start time.",
    ),
    Field(
        key="AUTO_CLICK_JOIN",
        type="bool",
        default=True,
        group="meetings",
        label="Try to press Join automatically",
        help="Best effort. Teams, Meet and Zoom change their web pages without "
        "notice, so if this fails the big JOIN button on the dashboard always works.",
    ),
    Field(
        key="JOIN_SETTLE_SECONDS",
        type="float",
        default=0.0,
        minimum=0.0,
        maximum=120.0,
        group="meetings",
        label="Wait before pressing anything (seconds)",
        help="0 uses a sensible per-provider default (6–8 seconds). Raise it on "
        "slower hardware: pressing buttons on a page that has not finished "
        "drawing wastes the whole join attempt. A Raspberry Pi 3 may need 25–40.",
        advanced=True,
    ),
    Field(
        key="AUTO_JOIN_TIMEOUT_SECONDS",
        type="int",
        default=90,
        minimum=10,
        maximum=600,
        group="meetings",
        label="Give up on auto-join after (seconds)",
        advanced=True,
    ),
    Field(
        key="JOIN_REPEAT_GUARD_SECONDS",
        type="float",
        default=25.0,
        minimum=0.0,
        maximum=300.0,
        group="meetings",
        label="Do not press the same button twice within (seconds)",
        help="A slow meeting page can look unchanged for several seconds after "
        "Join is pressed. Without this guard the room presses it again, and "
        "again, which looks like the meeting being opened several times over.",
        advanced=True,
    ),
    Field(
        key="RETURN_HOME_MINUTES",
        type="float",
        default=2.0,
        minimum=0.0,
        maximum=120.0,
        group="meetings",
        label="Return to dashboard after (minutes)",
        help="Grace period after a meeting's scheduled end before the TV goes "
        "back to the room screen.",
    ),
    Field(
        key="MAX_MEETING_MINUTES",
        type="int",
        default=240,
        minimum=10,
        maximum=1440,
        group="meetings",
        label="Hard limit on a meeting screen (minutes)",
        help="Safety net: the appliance never stays on a meeting page longer "
        "than this, even if the calendar goes strange.",
        advanced=True,
    ),
    Field(
        key="JOIN_BUTTON_TEXTS",
        type="list",
        default=[
            "Continue on this browser",
            "Use the web app instead",
            "Continue in this browser",
            "Join now",
            "Join meeting",
            "Join call",
            "Ask to join",
            "Join anyway",
            "Continue without audio or video",
            "Dismiss",
        ],
        group="meetings",
        label="Buttons the auto-join may press",
        help="One per line, matched case-insensitively against on-screen button "
        "text. Update this list if a provider renames a button — no code change needed.",
        advanced=True,
    ),
    Field(
        key="JOIN_DISPLAY_NAME",
        type="str",
        default="",
        group="meetings",
        label="Guest display name",
        help="Name typed into “your name” boxes when the room joins as a guest. "
        "Leave empty to use the room name.",
        placeholder="Meeting Room",
        advanced=True,
    ),
    Field(
        key="JOIN_MUTE_ON_ENTRY",
        type="bool",
        default=False,
        group="meetings",
        label="Join muted",
        help="Ask the meeting page to mute the room's microphone on entry.",
        advanced=True,
    ),
    # -- Room controller ----------------------------------------------------
    Field(
        key="CONTROLLER_ENABLED",
        type="bool",
        default=True,
        group="controller",
        label="Phone controller",
        help="A big-button page for whoever is in the room: join, leave, mute, "
        "camera and volume. It is opened by scanning the code on the TV — no "
        "app to install and no PIN to remember.",
    ),
    Field(
        key="CONTROLLER_QR_ON_TV",
        type="bool",
        default=True,
        group="controller",
        label="Show the QR code on the TV",
        help="A small code in the bottom-right corner of the room screen. Point "
        "a phone camera at it to open the controller for this room.",
    ),
    Field(
        key="CONTROLLER_LAN_ACCESS",
        type="bool",
        default=False,
        group="controller",
        label="Let phones on the room network open the controller",
        help="Needed for the QR code to work when “Allow settings from other "
        "computers on the network” is off. Nothing is reachable without the "
        "code on the TV or the admin PIN.",
        restart_units=("room-dashboard.service",),
    ),
    Field(
        key="CONTROLLER_FULL_ACCESS",
        type="bool",
        default=True,
        group="controller",
        label="A scanned phone can do everything",
        help="On, the QR code is this room's remote control: the room buttons, "
        "settings, backgrounds, restarts, logs — so a keyboard never has to be "
        "plugged into the Pi, not even for first-time setup. Off, a scanned "
        "phone gets the room buttons only and anything else asks for the admin "
        "PIN.",
    ),
    Field(
        key="CONTROLLER_REQUIRE_PIN",
        type="bool",
        default=False,
        group="controller",
        label="Ask for the admin PIN on the controller too",
        help="Turn this on for a room in a public space, where being able to see "
        "the TV should not be enough to control it.",
        advanced=True,
    ),
    # -- AirPlay ------------------------------------------------------------
    Field(
        key="AIRPLAY_ENABLED",
        type="bool",
        default=True,
        group="airplay",
        label="Enable AirPlay receiver",
        restart_units=("room-airplay.service",),
    ),
    Field(
        key="AIRPLAY_NAME",
        type="str",
        default="",
        group="airplay",
        label="AirPlay name",
        help="What appears in Screen Mirroring on a Mac or iPhone. Leave empty "
        "to use the room name.",
        placeholder="Meeting Room",
        restart_units=("room-airplay.service",),
    ),
    Field(
        key="AIRPLAY_PIN",
        type="password",
        default="",
        group="airplay",
        label="AirPlay PIN",
        help="Optional numeric PIN a guest must type to share their screen. "
        "Empty means anyone on the network can share.",
        secret=True,
        restart_units=("room-airplay.service",),
    ),
    Field(
        key="AIRPLAY_EXTRA_ARGS",
        type="str",
        default="",
        group="airplay",
        label="Extra UxPlay arguments",
        help="Appended to the uxplay command line for unusual setups.",
        advanced=True,
        restart_units=("room-airplay.service",),
    ),
    Field(
        key="AIRPLAY_INTERRUPTS_MEETING",
        type="bool",
        default=True,
        group="airplay",
        label="Allow screen sharing during a meeting",
        help="On: mirroring covers the meeting on the TV (the call keeps running). "
        "Off: mirroring is refused during a meeting. Either way, sharing through "
        "Teams or Meet is better, because remote participants can see it too.",
        advanced=True,
    ),
    # -- Poly conference bar -----------------------------------------------
    Field(
        key="POLY_ENABLED",
        type="bool",
        default=True,
        group="audio",
        label="Manage the conference bar",
        help="Detect the USB bar and make it the default camera, microphone and speaker.",
    ),
    Field(
        key="MICROPHONE_DEVICE",
        type="str",
        default="auto",
        group="audio",
        label="Microphone",
        help="“auto” picks the Poly bar automatically. Otherwise a PipeWire/"
        "PulseAudio source name — the Diagnostics page lists them.",
        placeholder="auto",
    ),
    Field(
        key="SPEAKER_DEVICE",
        type="str",
        default="auto",
        group="audio",
        label="Speaker",
        help="“auto” picks the Poly bar. Set to “hdmi” to play sound through "
        "the TV, or paste an exact sink name.",
        placeholder="auto",
    ),
    Field(
        key="CAMERA_DEVICE",
        type="str",
        default="auto",
        group="audio",
        label="Camera",
        help="“auto” picks the Poly bar, or give a device path such as /dev/video0.",
        placeholder="auto",
    ),
    Field(
        key="POLY_USB_MATCH",
        type="list",
        default=["poly", "plantronics", "polycom", "studio", "hp inc"],
        group="audio",
        label="USB name matches",
        help="Case-insensitive words used to recognise the bar in lsusb / PipeWire "
        "output. One per line. Add your model's name here if detection fails.",
        advanced=True,
    ),
    Field(
        key="POLY_STARTUP_VOLUME",
        type="int",
        default=65,
        minimum=0,
        maximum=100,
        group="audio",
        label="Startup volume (%)",
        help="Applied to the conference bar when the appliance starts. 0 disables.",
    ),
    Field(
        key="POLY_CHECK_SECONDS",
        type="int",
        default=20,
        minimum=5,
        maximum=600,
        group="audio",
        label="Device check interval (seconds)",
        advanced=True,
    ),
    # -- Poly remote --------------------------------------------------------
    Field(
        key="POLY_REMOTE_ENABLED",
        type="bool",
        default=False,
        group="remote",
        label="Enable remote / controller",
        help="Turn on if you have a Poly remote or controller. Use "
        "Diagnostics → Discover remote buttons to find the key names.",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_REMOTE_DEVICE",
        type="str",
        default="auto",
        group="remote",
        label="Input device",
        help="“auto” watches every matching input device. Otherwise an "
        "/dev/input/eventN path.",
        placeholder="auto",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_ANSWER_KEY",
        type="str",
        default="KEY_ENTER",
        group="remote",
        label="Answer / green button",
        help="Joins the current or next meeting.",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_HANGUP_KEY",
        type="str",
        default="KEY_ESC",
        group="remote",
        label="Hang-up / red button",
        help="Leaves the meeting and returns to the dashboard.",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_MUTE_KEY",
        type="str",
        default="KEY_MUTE",
        group="remote",
        label="Mute button",
        help="Toggles the microphone.",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_VOLUME_UP_KEY",
        type="str",
        default="KEY_VOLUMEUP",
        group="remote",
        label="Volume up button",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_VOLUME_DOWN_KEY",
        type="str",
        default="KEY_VOLUMEDOWN",
        group="remote",
        label="Volume down button",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_CAMERA_KEY",
        type="str",
        default="",
        group="remote",
        label="Camera button",
        help="Optional. Toggles the camera in the meeting where supported.",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_HOME_KEY",
        type="str",
        default="KEY_HOME",
        group="remote",
        label="Home button",
        help="Forces the TV back to the room dashboard.",
        restart_units=("room-remote.service",),
    ),
    Field(
        key="POLY_VOLUME_STEP",
        type="int",
        default=5,
        minimum=1,
        maximum=25,
        group="remote",
        label="Volume step (%)",
        advanced=True,
        restart_units=("room-remote.service",),
    ),
    # -- Display & browser --------------------------------------------------
    Field(
        key="KIOSK_ENABLED",
        type="bool",
        default=True,
        group="display",
        label="Run the Chromium kiosk",
        help="Turn off only when developing on a normal computer.",
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="CHROMIUM_BINARY",
        type="str",
        default="auto",
        group="display",
        label="Chromium binary",
        help="“auto” searches for chromium-browser, chromium then "
        "google-chrome.",
        advanced=True,
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="CHROMIUM_DEBUG_PORT",
        type="int",
        default=9222,
        minimum=1024,
        maximum=65535,
        group="display",
        label="Chromium debug port (localhost only)",
        help="Used by the appliance to drive the browser. Never exposed off the Pi.",
        advanced=True,
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="PERFORMANCE_PROFILE",
        type="choice",
        default="auto",
        choices=("auto", "high", "balanced", "low"),
        group="display",
        label="Performance profile",
        help="“auto” looks at the machine and picks: a mini-PC or NUC gets "
        "“high” (GPU rasterisation and video decoding on, join timings "
        "unpadded), a Pi 4 or 5 gets “balanced”, a Pi 3 gets “low”. Choose one "
        "by hand to override the guess. It only ever supplies defaults — "
        "anything you have set yourself still wins.",
        restart_units=("room-dashboard.service", "room-kiosk.service"),
    ),
    Field(
        key="CHROMIUM_RENDER_MODE",
        type="choice",
        default="auto",
        choices=("auto", "wayland", "x11", "software"),
        group="display",
        label="How Chromium draws to the TV",
        help="Fix for a blank or white screen. “auto” detects Wayland (the "
        "default on Raspberry Pi OS Bookworm). Try “wayland”, then “x11”, then "
        "“software” — software always renders but without GPU acceleration.",
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="CHROMIUM_EXTRA_ARGS",
        type="str",
        default="",
        group="display",
        label="Extra Chromium arguments",
        advanced=True,
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="HIDE_CURSOR",
        type="bool",
        default=True,
        group="display",
        label="Hide the mouse pointer",
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="SCREEN_BLANKING",
        type="bool",
        default=False,
        group="display",
        label="Allow the screen to blank",
        help="Off keeps the dashboard visible at all times.",
        restart_units=("room-kiosk.service",),
    ),
    Field(
        key="THEME",
        type="choice",
        default="dark",
        choices=("dark", "light"),
        group="display",
        label="Dashboard theme",
    ),
    Field(
        key="ACCENT_COLOR",
        type="str",
        default="#3d8bfd",
        group="display",
        label="Accent colour",
        help="Hex colour used for the JOIN button and highlights.",
        advanced=True,
    ),
    Field(
        key="SHOW_SHARING_INSTRUCTIONS",
        type="bool",
        default=True,
        group="display",
        label="Show screen-sharing instructions",
    ),
    Field(
        key="SHOW_STATUS_INDICATORS",
        type="bool",
        default=True,
        group="display",
        label="Show system status indicators",
        help="The small camera / microphone / network dots along the bottom.",
    ),
    # -- Background & slideshow --------------------------------------------
    Field(
        key="BACKGROUND_MODE",
        type="choice",
        default="theme",
        choices=("theme", "slideshow", "solid"),
        group="background",
        label="Background",
        help="“theme” is the built-in gradient. “slideshow” rotates through the "
        "images you upload in the control panel. “solid” is a single colour.",
    ),
    Field(
        key="BACKGROUND_SLIDESHOW_SECONDS",
        type="int",
        default=45,
        minimum=5,
        maximum=3600,
        group="background",
        label="Seconds per image",
        help="How long each slideshow image stays on screen before it fades to "
        "the next. Videos ignore this and play to the end.",
    ),
    Field(
        key="BACKGROUND_VIDEO_SOUND",
        type="bool",
        default=False,
        group="background",
        label="Play sound with background videos",
        help="Off by default, and it should usually stay off: the wallpaper "
        "talking over a meeting is worse than a silent clip.",
    ),
    Field(
        key="BACKGROUND_SHUFFLE",
        type="bool",
        default=True,
        group="background",
        label="Shuffle images",
        help="Off plays them in filename order.",
    ),
    Field(
        key="BACKGROUND_DIM_PERCENT",
        type="int",
        default=55,
        minimum=0,
        maximum=95,
        group="background",
        label="Darken images by (%)",
        help="Keeps the time and meeting text readable over a bright photo. "
        "Raise it if the text is hard to read from across the room.",
    ),
    Field(
        key="BACKGROUND_BLUR_PIXELS",
        type="int",
        default=0,
        minimum=0,
        maximum=40,
        group="background",
        label="Blur images by (pixels)",
        help="A little blur makes busy photos easier to read text over.",
    ),
    Field(
        key="BACKGROUND_SOLID_COLOR",
        type="str",
        default="#0b1220",
        group="background",
        label="Solid colour",
        help="Used when Background is set to “solid”.",
        advanced=True,
    ),
    Field(
        key="BACKGROUND_ALLOW_UPLOADS",
        type="bool",
        default=True,
        group="background",
        label="Allow image uploads from the control panel",
        help="Turn off to freeze the slideshow contents.",
        advanced=True,
    ),
    # -- Reliability --------------------------------------------------------
    Field(
        key="HEALTH_CHECK_SECONDS",
        type="int",
        default=15,
        minimum=5,
        maximum=300,
        group="recovery",
        label="Health check interval (seconds)",
        advanced=True,
    ),
    Field(
        key="NETWORK_CHECK_HOSTS",
        type="list",
        default=["1.1.1.1", "8.8.8.8"],
        group="recovery",
        label="Hosts used to test internet access",
        help="One per line.",
        advanced=True,
    ),
    Field(
        key="AUTO_RECOVER_BROWSER",
        type="bool",
        default=True,
        group="recovery",
        label="Recover a stuck browser",
        help="If Chromium stops responding or drifts to an unexpected page, put "
        "it back on the dashboard.",
    ),
    Field(
        key="WATCHDOG_ENABLED",
        type="bool",
        default=True,
        group="recovery",
        label="External watchdog",
        help="A tiny timer outside the app checks the appliance every minute and "
        "restarts anything that has stopped answering.",
        restart_units=("room-watchdog.timer",),
    ),
    Field(
        key="WATCHDOG_REBOOT_ENABLED",
        type="bool",
        default=True,
        group="recovery",
        label="Reboot as a last resort",
        help="If the appliance cannot be revived by restarting services, reboot "
        "the Pi. Rate-limited to once an hour.",
    ),
    Field(
        key="WATCHDOG_REBOOT_AFTER_FAILURES",
        type="int",
        default=10,
        minimum=3,
        maximum=120,
        group="recovery",
        label="Failed checks before rebooting",
        help="With a 1-minute watchdog, 10 means roughly ten minutes of being "
        "completely unresponsive.",
        advanced=True,
    ),
    Field(
        key="AUTO_UPDATE_ON_BOOT",
        type="bool",
        default=True,
        group="recovery",
        label="Update the room software when it boots",
        help="Pulls the latest version from the repository this room was "
        "installed from, before the dashboard starts. A room that cannot reach "
        "the repository, or whose files have been edited on the Pi, simply "
        "keeps the version it has — updating never stops the room starting.",
        restart_units=(),
    ),
    Field(
        key="AUTO_UPDATE_BRANCH",
        type="str",
        default="",
        group="recovery",
        label="Branch to update from",
        help="Empty follows whichever branch the Pi is on. Only fast-forward "
        "updates are taken, so a branch that has diverged is left alone.",
        placeholder="main",
        advanced=True,
    ),
    Field(
        key="DAILY_RESTART_TIME",
        type="str",
        default="",
        group="recovery",
        label="Daily quiet-hours restart",
        help="Optional HH:MM (24-hour) at which the room software restarts itself "
        "while nobody is around, e.g. 04:30. Empty disables it.",
        placeholder="04:30",
    ),
    # -- System -------------------------------------------------------------
    Field(
        key="DASHBOARD_PORT",
        type="int",
        default=8080,
        minimum=1,
        maximum=65535,
        group="system",
        label="Dashboard port",
        help="Change this if another program already uses the port. The TV and "
        "the control-panel address both follow it.",
        # The kiosk builds the dashboard URL from this at launch, so it needs
        # restarting too — otherwise Chromium keeps loading the old port and
        # the TV goes blank.
        restart_units=("room-dashboard.service", "room-kiosk.service"),
    ),
    Field(
        key="DASHBOARD_HOST",
        type="str",
        default="127.0.0.1",
        group="system",
        label="Listen address",
        help="127.0.0.1 keeps the dashboard on the Pi itself. Use the LAN admin "
        "switch below rather than editing this by hand.",
        advanced=True,
        validator=_validate_host,
        restart_units=("room-dashboard.service",),
    ),
    Field(
        key="ADMIN_LAN_ACCESS",
        type="bool",
        default=False,
        group="system",
        label="Allow settings from other computers on the network",
        help="Lets you open the Settings page from a laptop instead of plugging a "
        "keyboard into the Pi. Requires an admin PIN.",
        restart_units=("room-dashboard.service",),
    ),
    Field(
        key="ADMIN_PIN",
        type="password",
        default="",
        group="system",
        label="Admin PIN",
        inputmode="numeric",
        help="Digits only. Required before network access to the Settings page "
        "can be switched on.",
        secret=True,
        validator=_validate_pin,
    ),
    Field(
        key="PANEL_ENABLED",
        type="bool",
        default=True,
        group="system",
        label="Enable the phone control panel",
        help="The simplified touch page at /panel used to join meetings, change "
        "the background and restart things from a phone.",
    ),
    Field(
        key="PANEL_SHOW_URL_ON_TV",
        type="bool",
        default=True,
        group="system",
        label="Show the control-panel address on the TV",
        help="Displays the http://…:8080/panel address in the corner of the "
        "dashboard so anyone can find it. Turn off once the room is set up.",
    ),
    Field(
        key="LOG_LEVEL",
        type="choice",
        default="INFO",
        choices=("DEBUG", "INFO", "WARNING", "ERROR"),
        group="system",
        label="Log level",
        help="DEBUG is noisy but useful while setting the room up.",
    ),
    Field(
        key="LOG_FORMAT",
        type="choice",
        default="text",
        choices=("text", "json"),
        group="system",
        label="Log format",
        help="“text” is easy to read in journalctl; “json” suits log collectors.",
        advanced=True,
    ),
    # -- Meeting minutes ----------------------------------------------------
    Field(
        key="MINUTES_ENABLED",
        type="bool",
        default=False,
        group="minutes",
        label="Record and write up meetings",
        help="The master switch. With this off nothing below runs, nothing is "
        "recorded, and the appliance behaves exactly as it did before.",
    ),
    Field(
        key="MINUTES_SHOW_RECORDING_NOTICE",
        type="bool",
        default=True,
        group="minutes",
        label="Show “this meeting is being recorded” on the TV",
        help="A badge on the room screen for as long as a recording is running. "
        "Leave this on. People are entitled to know, and a room that tells them "
        "is a room they keep trusting.",
    ),
    Field(
        key="MINUTES_RECORD_ROOM",
        type="bool",
        default=True,
        group="minutes",
        label="Record the room microphone",
        help="The people physically in the room, from the conference bar.",
    ),
    Field(
        key="MINUTES_RECORD_FAR_END",
        type="bool",
        default=True,
        group="minutes",
        label="Record what the room hears",
        help="Everyone dialled in, taken from the speaker's own output. Recorded "
        "as a second, separate track — which is what lets the transcript say "
        "for certain whether a voice was in the room or on the call.",
    ),
    Field(
        key="MINUTES_MIN_MEETING_SECONDS",
        type="int",
        default=120,
        minimum=0,
        maximum=3600,
        group="minutes",
        label="Ignore meetings shorter than (seconds)",
        help="A meeting joined and left again in half a minute is a misfire, not "
        "a meeting. Below this it is deleted rather than written up.",
    ),
    Field(
        key="MINUTES_MAX_MEETING_MINUTES",
        type="int",
        default=240,
        minimum=5,
        maximum=1440,
        group="minutes",
        label="Stop recording after (minutes)",
        help="A guard against a meeting nobody ever left filling the SD card.",
        advanced=True,
    ),
    Field(
        key="MINUTES_KEEP_AUDIO_DAYS",
        type="int",
        default=0,
        minimum=0,
        maximum=365,
        group="minutes",
        label="Keep the audio for (days)",
        help="0 deletes the recording the moment it has been transcribed, which "
        "is the right answer for almost everyone: the transcript is the useful "
        "artefact and the audio is the sensitive one.",
    ),
    Field(
        key="MINUTES_KEEP_DAYS",
        type="int",
        default=30,
        minimum=1,
        maximum=3650,
        group="minutes",
        label="Keep transcripts and summaries for (days)",
        help="Older meetings are deleted from the Pi. Anything emailed out has "
        "already left and is not affected.",
    ),
    # -- Speech to text -----------------------------------------------------
    Field(
        key="MINUTES_STT_ENGINE",
        type="choice",
        default="auto",
        choices=("auto", "whisper-cpp", "faster-whisper", "vosk", "none"),
        group="minutes",
        label="Speech-to-text engine",
        help="“auto” uses whichever of these is actually installed, best first. "
        "“none” records the audio and identifies who spoke, but writes no words — "
        "useful on hardware too slow to transcribe. See docs/meeting-minutes.md "
        "for how to install one.",
    ),
    Field(
        key="MINUTES_STT_MODEL",
        type="str",
        default="",
        group="minutes",
        label="Speech-to-text model",
        help="Path to a whisper.cpp model file or a vosk model directory. Leave "
        "empty to use whatever was found in var/minutes/models.",
        placeholder="/opt/whisper/ggml-base.en.bin",
        advanced=True,
    ),
    Field(
        key="MINUTES_STT_LANGUAGE",
        type="str",
        default="en",
        group="minutes",
        label="Spoken language",
        help="Two-letter language code passed to the engine. “auto” lets whisper "
        "detect it, at some cost in speed and accuracy.",
        placeholder="en",
        advanced=True,
    ),
    # -- Who was speaking ---------------------------------------------------
    Field(
        key="MINUTES_IDENTIFY_REMOTE",
        type="bool",
        default=True,
        group="minutes",
        label="Name remote speakers from the meeting window",
        help="Reads the participant list and the active-speaker highlight out of "
        "the Teams, Meet or Zoom page. This is by far the most reliable way to "
        "know who said something on a call, because the meeting app already knows.",
    ),
    Field(
        key="MINUTES_READ_CAPTIONS",
        type="bool",
        default=True,
        group="minutes",
        label="Use the meeting's own live captions",
        help="When somebody has live captions switched on, Teams and Google Meet "
        "already write down what each remote person said and put their name on "
        "it. Reading that is far more accurate than transcribing the call audio "
        "here, and costs the Raspberry Pi nothing.",
    ),
    Field(
        key="MINUTES_TURN_ON_CAPTIONS",
        type="bool",
        default=False,
        group="minutes",
        label="Switch live captions on when joining",
        help="Off by default on purpose: captions appear on the TV for everyone "
        "in the room, so switching them on is a visible change to the meeting "
        "and should be somebody's decision rather than a side effect.",
    ),
    Field(
        key="MINUTES_OPEN_ROSTER",
        type="bool",
        default=False,
        group="minutes",
        label="Open the participant list when joining",
        help="Some meetings only name everyone once the participant panel is "
        "open. Off by default because the panel appears on the TV and shrinks "
        "everyone's video — a visible change to the meeting for the sake of a "
        "few more names in the transcript.",
        advanced=True,
    ),
    Field(
        key="MINUTES_IDENTIFY_FACES",
        type="bool",
        default=False,
        group="minutes",
        label="Recognise faces in the room (experimental)",
        help="Looks at the room through the conference-bar camera between "
        "meetings and notes which enrolled colleagues are present. It cannot look "
        "during a meeting — the camera belongs to the meeting then — so the "
        "roster is whoever was seen just before the meeting started. Expect it to "
        "name most people within about two metres of the bar, to get steadily "
        "worse past three, and to see nobody at all at the far end of a long "
        "table. Backlighting, a turned head and a late arrival all defeat it.",
    ),
    Field(
        key="MINUTES_IDENTIFY_VOICES",
        type="bool",
        default=False,
        group="minutes",
        label="Recognise voices in the room (experimental)",
        help="Matches each in-room speaking turn against enrolled voice profiles. "
        "Genuinely hard on a far-field microphone in a room with hard walls: "
        "expect it to be useful as a suggestion you correct, not as an answer you "
        "trust. Even when it cannot name anybody it still keeps two speakers "
        "apart, which is worth having on its own — and correcting a name in a "
        "transcript afterwards is what teaches it.",
    ),
    Field(
        key="MINUTES_FACE_THRESHOLD",
        type="float",
        default=0.40,
        minimum=0.05,
        maximum=0.95,
        group="minutes",
        label="Face match threshold",
        help="How similar a face must be to count as a match. Higher is stricter: "
        "raise it if the room starts calling people by the wrong name.",
        advanced=True,
    ),
    Field(
        key="MINUTES_VOICE_THRESHOLD",
        type="float",
        default=0.62,
        minimum=0.05,
        maximum=0.99,
        group="minutes",
        label="Voice match threshold",
        help="How similar a voice must be to count as a match. Higher is stricter.",
        advanced=True,
    ),
    Field(
        key="MINUTES_ROOM_SCAN_SECONDS",
        type="int",
        default=90,
        minimum=15,
        maximum=3600,
        group="minutes",
        label="Look at the room every (seconds)",
        help="How often to check who is in the room while no meeting is running. "
        "More often means a fresher roster and more work for the Pi.",
        advanced=True,
    ),
    # -- The summary --------------------------------------------------------
    Field(
        key="MINUTES_SUMMARY_ENABLED",
        type="bool",
        default=False,
        group="minutes",
        label="Write a summary with Claude",
        help="Sends the transcript to the Claude API and gets back a summary with "
        "decisions and action points. The transcript leaves the appliance when "
        "this is on — that is the whole point of it, and worth being deliberate "
        "about.",
    ),
    Field(
        key="MINUTES_CLAUDE_API_KEY",
        type="password",
        default="",
        group="minutes",
        label="Claude API key",
        secret=True,
        help="From console.anthropic.com. Stored on the Pi in config.yaml, "
        "readable only by the appliance's own user, and never shown again here.",
        placeholder="sk-ant-…",
        validator=_validate_api_key_or_empty,
    ),
    Field(
        key="MINUTES_CLAUDE_MODEL",
        type="choice",
        default="claude-opus-5",
        choices=("claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5"),
        group="minutes",
        label="Claude model",
        help="Opus writes the best summaries. Sonnet is cheaper and very close. "
        "Haiku is cheapest and noticeably blunter.",
    ),
    Field(
        key="MINUTES_SUMMARY_EFFORT",
        type="choice",
        default="medium",
        choices=("low", "medium", "high"),
        group="minutes",
        label="How hard Claude should think",
        help="A summary is not a hard problem, so “medium” is the sensible "
        "setting. “high” costs more for little gain on a normal meeting.",
        advanced=True,
    ),
    Field(
        key="MINUTES_SUMMARY_INSTRUCTIONS",
        type="text",
        default="",
        group="minutes",
        label="Extra instructions for the summary",
        help="Added to the prompt. Use it for house style: which sections you "
        "want, how long, whether to always list owners and dates.",
        placeholder="Always end with a table of action points, owner and due date.",
    ),
    Field(
        key="MINUTES_SUMMARY_CONTEXT_MEETINGS",
        type="int",
        default=3,
        minimum=0,
        maximum=10,
        group="minutes",
        label="Include this many earlier summaries",
        help="Summaries of previous meetings with the same title are put in front "
        "of the transcript, so a recurring meeting is written up knowing what was "
        "agreed last time. 0 turns that off.",
        advanced=True,
    ),
    # -- Sending it out -----------------------------------------------------
    Field(
        key="MINUTES_EMAIL_ENABLED",
        type="bool",
        default=False,
        group="minutes",
        label="Email the summary",
        help="Sends the finished summary to the people who were in the meeting.",
    ),
    Field(
        key="MINUTES_SMTP_HOST",
        type="str",
        default="",
        group="minutes",
        label="SMTP server",
        help="Your mail provider's outgoing server.",
        placeholder="smtp.gmail.com",
    ),
    Field(
        key="MINUTES_SMTP_PORT",
        type="int",
        default=587,
        minimum=1,
        maximum=65535,
        group="minutes",
        label="SMTP port",
        help="587 for STARTTLS, 465 for implicit TLS.",
    ),
    Field(
        key="MINUTES_SMTP_SECURITY",
        type="choice",
        default="starttls",
        choices=("starttls", "ssl", "none"),
        group="minutes",
        label="SMTP security",
        help="“starttls” with port 587 is what almost every provider wants. "
        "“none” sends your password in the clear and is only ever right for a "
        "relay on your own network.",
    ),
    Field(
        key="MINUTES_SMTP_USERNAME",
        type="str",
        default="",
        group="minutes",
        label="SMTP username",
        help="Usually the full email address of the account sending the summary.",
        placeholder="room@example.com",
    ),
    Field(
        key="MINUTES_SMTP_PASSWORD",
        type="password",
        default="",
        group="minutes",
        label="SMTP password",
        secret=True,
        help="With Gmail or Microsoft 365 this must be an app password, not the "
        "account password.",
    ),
    Field(
        key="MINUTES_EMAIL_FROM",
        type="str",
        default="",
        group="minutes",
        label="Send from",
        help="The address the summary appears to come from. Leave empty to use "
        "the SMTP username.",
        placeholder="room@example.com",
        validator=_validate_email_or_empty,
    ),
    Field(
        key="MINUTES_EMAIL_TO_ATTENDEES",
        type="bool",
        default=True,
        group="minutes",
        label="Send to the people who were invited",
        help="Uses the attendee list from the calendar invitation, plus anyone "
        "the appliance recognised in the room. Off means only the fixed list below.",
    ),
    Field(
        key="MINUTES_EMAIL_ALWAYS_TO",
        type="list",
        default=[],
        group="minutes",
        label="Always also send to",
        help="One address per line. A good place for the person who owns this "
        "appliance, so you can see what is going out.",
        placeholder="charlie@example.com",
        validator=_validate_email_list,
    ),
    Field(
        key="MINUTES_EMAIL_ATTACH_TRANSCRIPT",
        type="bool",
        default=False,
        group="minutes",
        label="Attach the full transcript",
        help="Adds the whole transcript as a text file. Off sends the summary "
        "only, which is what most people want in their inbox.",
    ),
    # -- System -------------------------------------------------------------
    Field(
        key="DEV_MODE",
        type="bool",
        default=False,
        group="system",
        label="Development mode",
        help="Runs with mock hardware so the dashboard can be built on a laptop. "
        "Never leave this on in a real room.",
        advanced=True,
    ),
)

FIELDS_BY_KEY: dict[str, Field] = {f.key: f for f in FIELDS}

#: Keys whose values must never be written to a log line or a JSON API response.
SECRET_KEYS: frozenset[str] = frozenset(f.key for f in FIELDS if f.secret)


def defaults() -> dict[str, Any]:
    """A fresh, fully-populated configuration dictionary."""
    out: dict[str, Any] = {}
    for f in FIELDS:
        out[f.key] = list(f.default) if isinstance(f.default, list) else f.default
    return out


def grouped_fields(include_advanced: bool = True) -> list[tuple[str, str, str, list[Field]]]:
    """Fields arranged for the Settings UI: ``(id, title, help, fields)``."""
    out = []
    for gid, title in GROUPS:
        members = [
            f for f in FIELDS if f.group == gid and (include_advanced or not f.advanced)
        ]
        if members:
            out.append((gid, title, GROUP_HELP.get(gid, ""), members))
    return out


def restart_units_for(keys: Iterable[str]) -> list[str]:
    """systemd units that need restarting after ``keys`` changed."""
    units: list[str] = []
    for key in keys:
        f = FIELDS_BY_KEY.get(key)
        if not f:
            continue
        for unit in f.restart_units:
            if unit not in units:
                units.append(unit)
    return units
